Meta-Llama-3.1-8B-Instruct-FW-FP8:
  prompt_template: "Mixtral-8x7B-Instruct-v0.1/togetherai_prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "accounts/fireworks/models/llama-v3p1-405b-instruct"
    max_tokens: 4096
    requires_chatml: True
    client_kwargs:
      base_url: 'https://api.fireworks.ai/inference/v1/'
  pretty_name: "Llama 3.1 8B Instruct"
  link: "https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct"